### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by dgthomson** [RagingTiger/shairport-sync#1]
Would you be able to enable the MQTT facilities in your fork of shairport-sync? I've worked out that you'll need the library 'mosquitto-dev' and the configure switch '--with-mqtt-client'.

I've been messing with forking the code and in Docker Hub but... let's just say I'm in well above my head!

**Comment by RagingTiger** [comment]
@dgthomson Don't worry, it is a lot to learn.

Apologies for not responding sooner, I just saw this issue (for some reason I was not notified). But you were able to fork the repo, and implement your changes (666f3a30975a93ee87ba953dc8eb65ce8deca8fa).

How has the addition of the **MQTT** functionality been? What use cases have you used the functionality for? Any problems or unforeseen errors/complications?

Thank you again for you interest, and apologies for not responding sooner.

**Comment by dgthomson** [comment]
@RagingTiger Thanks. I was completely unsuccessful getting MQTT working. I even built the code outside Docker with no luck. I ended up piping the shairport metadata to a file, then using a Node-red 'tail' node to pick it up, format it and pass it to Alexa to announce the song name. TBH it was a time-wasting exercise during lockdown (I'm sure you understand!) so I haven't really used it much.

**Comment by RagingTiger** [comment]
@dgthomson I see. But you did get the **Docker image** to work as you wanted, just not the actual feature (i.e. **MQTT**) to work?

Glad you found a work around 😅

**Comment by sofakng** [comment]
I'd like to see MQTT support added too.

The main purpose is to send an MQTT message to turn-on my amplifier (using a Tasmota/ESP8266 relay switch).

**Comment by RagingTiger** [comment]
This repository will be made **read only** since I am not actively maintaining it.

I have found a viable alternative that may address your **MQTT** use case: https://github.com/mikebrady/shairport-sync#what-else

Best of luck, hopefully there are better options out there for your use case 😄
